Repository andsfonseca/dota2-rpc-client, pull requests merged in 2022-08, with the labels that each got.

#24 [Fix] Considering any game with the number 570 as Dota
  include/extensions/StringExtensions.h
  lang/en-us.json
  lang/es-es.json
  lang/pt-br.json
  lang/ru-ru.json
  lang/uk-ua.json
  main.cc
  src/extensions/StringExtensions.cpp
  src/managers/SteamManager.cpp
Labels: bug

#25 [Feature] Automatic Close Issues
  .github/workflows/issues.yml
Labels: enhancement

#26 Localization updates for Russian and Ukrainian
  lang/ru-ru.json
  lang/uk-ua.json
Labels: translation, implemented
